image:
  file: .gitpod.Dockerfile

ports:
  - port: 3007
    onOpen: open-browser
    visibility: public
  - port: 3006
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - graphql.vscode-graphql
    - yzhang.markdown-all-in-one
    - ms-vscode.vscode-typescript-tslint-plugin
    - hediet.vscode-drawio
    - ms-azuretools.vscode-docker

tasks:
  - init: npm run gitpod-prepare; gp open readme.md; npm ci; npm run packages; npm run git-shh-to-https; npm run gitpod-setup;
  - command: npm run gitpod-wakeup;
  
